import secrets
import hashlib

class OTPService:
    """
    OTP Cryptographic Service.
    Responsible solely for generating secure random 6-digit codes,
    hashing them for secure database storage, and verifying matches
    using timing-attack resistant comparisons.
    """

    @staticmethod
    def generate_otp() -> str:
        """
        Generates a secure cryptographically random 6-digit verification code.
        """
        # SystemRandom uses os.urandom internally, providing secure entropy suitable for crypto
        # ponytail: standard library secrets provides excellent random int generator in 1 line
        return str(secrets.SystemRandom().randint(100000, 999999))

    @staticmethod
    def hash_otp(otp: str) -> str:
        """
        Hashes the 6-digit OTP using SHA-256.
        Since OTPs are high-entropy (6 digits generated by CSPRNG) and expire quickly,
        a fast cryptographic hash like SHA-256 is ideal for performance and database storage.
        """
        return hashlib.sha256(otp.encode('utf-8')).hexdigest()

    @staticmethod
    def verify_otp(plain_otp: str, hashed_otp: str) -> bool:
        """
        Verifies if the provided plain OTP matches the stored hash.
        Uses secrets.compare_digest to defend against timing attacks.
        """
        computed_hash = hashlib.sha256(plain_otp.encode('utf-8')).hexdigest()
        return secrets.compare_digest(computed_hash, hashed_otp)
